In [1]:
import pytorch_lightning as pl
from torch.utils.data import random_split, DataLoader
import os
import torch
import json

In [3]:
folder_dir_DW="./data/PytorchFiles"
i=0
datadir=sorted(os.listdir(folder_dir_DW))
newlist=[]


for file_name in datadir[1:]:
    if os.path.getsize((folder_dir_DW +"/" + file_name)) ==37749483:
        file=torch.load(folder_dir_DW +"/" + file_name)
        file= file.type(torch.float32)
        file[:,1]= torch.nn.functional.relu(file[:,1])/4219.
        file= file.type(torch.float16)
        tmp = torch.transpose(torch.transpose(torch.transpose(file,0,2),1,2),0,1)
        reshaped = torch.reshape(tmp, (8*12,3,256,256))
        reshaped = reshaped[:,0,].unsqueeze(1)
        newlist.append(reshaped)        

    else:
        
        if len(newlist)==0:
            continue
        else:
            torch.save(torch.cat(newlist),"./data/16bit_1dim/chunk"+ str(i)+".pt")
            i+=1
            newlist=[]
            


  
        
    


In [5]:
(len(datadir)-2)/2

365.0

In [25]:
file[:,1]= torch.nn.functional.relu(file[:,1])/4219.

In [29]:
file=file.type(torch.float16)

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.3010, 0.3420, 0.3464,  ..., 0.0000, 0.0000, 0.0000],
          [0.2576, 0.2737, 0.2781,  ..., 0.0000, 0.0000, 0.0000],
          [0.2988, 0.2401, 0.2769,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.3010, 0.3420, 0.3464,  ..., 0.0000, 0.0000, 0.0000],
          [0.2576, 0.2737, 0.2781,  ..., 0.0000, 0.0000, 0.0000],
          [0.2988, 0.2401, 0.2769,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

In [16]:
file2= file.type(torch.float16)

In [18]:
file2.dtype

torch.float16

In [19]:
test = torch.nn.functional.relu(file2[:,1,:,:,:])/4219.



RuntimeError: "clamp_min_cpu" not implemented for 'Half'

In [13]:
test.dtype

torch.float32

In [37]:
file[:,2,:,:,:]

tensor([[[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0]],

         ...,

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0],
          [1, 1, 1,  ..., 0, 0, 0]],

         [[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 

In [2]:
folder_dir_ch="./data/DoneFolder"
chunks=sorted(os.listdir(folder_dir_ch))
final_list = []
chunklist=[]
seqlen=7
window=3

j=0

for chunk in chunks[1:]:
    print(chunk)
    file=torch.load(folder_dir_ch +"/" + chunk)
    for i in range(0,file.shape[0], window):
        if i<file.shape[0]-seqlen:
            chunklist.append(file[i:seqlen+i,:,:,:])
        else:
            break

            
        
        
        
    
    

chunk0.pt
chunk1.pt
chunk10.pt
chunk11.pt
chunk12.pt
chunk2.pt
chunk3.pt
chunk4.pt
chunk5.pt
chunk6.pt
chunk7.pt
chunk8.pt
chunk9.pt


In [4]:
chunklist[0].shape

torch.Size([1, 7, 3, 256, 256])

In [5]:
from torch.utils.data import Dataset, DataLoader

In [6]:
class mydata(Dataset):
    def __init__(self, datalist):
        self.data= datalist
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data[idx]

In [7]:
test= mydata(chunklist)

In [9]:
testloader= DataLoader(test, batch_size=2, shuffle=True)


In [10]:
for x in testloader:
    print(x.shape)
    break

torch.Size([2, 1, 7, 3, 256, 256])


In [4]:
with open("data.json", "w") as f:
    json.dump(chunklist, f)

TypeError: Object of type Tensor is not JSON serializable

In [6]:
import numpy as np

In [ ]:
np.save("mydata.npy", chunklist)

/home/triston/.conda/envs/skipconnect/lib/python3.9/site-packages/numpy/lib/npyio.py:528: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  arr = np.asanyarray(arr)
/home/triston/.conda/envs/skipconnect/lib/python3.9/site-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


In [ ]:
final = torch.cat(final_list)

In [3]:
i=1335

In [4]:
data_0 = torch.cat(chunklist[:i])
data_1 =torch.cat(chunklist[i:i*2])

In [5]:
data_2 =torch.cat(chunklist[i*2:i*3])
data_3 =torch.cat(chunklist[i*3:i*4])





In [6]:
data_4 =torch.cat(chunklist[i*4:i*5])
data_5 =torch.cat(chunklist[i*5:i*6])

In [ ]:
data_6 =torch.cat(chunklist[i*6:i*7])
data_7 =torch.cat(chunklist[i*7:i*8])

In [ ]:
data_8 =torch.cat(chunklist[i*8:i*9])
data_9 =torch.cat(chunklist[i*9:])

In [1]:
data_9.shape

NameError: name 'data_9' is not defined

In [7]:
third_tensor= tf.concat(0, [data_0, data_1])

13350

In [ ]:
banan.shape

In [21]:
(10272-7)/3+1

3422.6666666666665

In [63]:
print(file[10272].shape)

torch.Size([3, 256, 256])


In [41]:
print(file)

tensor([[[[[   0,    0,    0,  ...,    1,    1,    1],
           [   0,    0,    0,  ...,    0,    0,    0],
           [   0,    0,    0,  ...,    0,    0,    0],
           ...,
           [   1,    1,    1,  ...,    0,    0,    0],
           [   1,    1,    1,  ...,    0,    0,    0],
           [   1,    1,    1,  ...,    0,    0,    0]],

          [[   0,    0,    0,  ...,    1,    1,    1],
           [   0,    0,    0,  ...,    1,    1,    1],
           [   0,    0,    0,  ...,    0,    0,    1],
           ...,
           [   0,    0,    0,  ...,    0,    0,    0],
           [   1,    1,    1,  ...,    0,    0,    0],
           [   1,    1,    1,  ...,    0,    0,    0]],

          [[   0,    0,    0,  ...,    1,    1,    1],
           [   0,    0,    0,  ...,    1,    1,    1],
           [   0,    0,    0,  ...,    1,    1,    1],
           ...,
           [   1,    0,    0,  ...,    0,    0,    0],
           [   1,    1,    1,  ...,    0,    0,    0],
           [ 

In [34]:
print(i)

16
